name: Release

on:
  workflow_dispatch:
  
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
      
jobs:
  release:
    if: github.event.pull_request.merged == true
    
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Git Config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTION}@users.noreply.github.com"

    - name: Install Depenencies
      run: npm install
      
    - name: Build and Release
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
