name: Build and Release

on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Depenencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: 'virginia-gc-extension.zip'
        path: dist/
    
    - name: Release
      run: npx release-it --ci --patch --no-npm --github.release --github.update --github.assets=*.zip --no-github.draft
