name: Build

on:
  push:
    branches: [ feature-cicd ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Depenencies
      uses: npm install

    - name: Build
      uses: npm run build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: dist/
